import React from 'react'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Button } from "@/components/ui/button";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <div className="relative min-h-screen overflow-hidden">
          <div className="gradient-background" />
          
          {/* Navigation */}
          <nav className="fixed top-5 left-0 right-0 z-50">
            <div className="flex items-center justify-center h-16 px-4 backdrop-blur-sm bg-background/10">
              <div className="flex gap-8">
                <Button variant="ghost" className="text-white/70 hover:text-white hover:bg-white/10">
                  About
                </Button>
                <Button variant="ghost" className="text-white/70 hover:text-white hover:bg-white/10">
                  Learn
                </Button>
                <Button variant="ghost" className="text-white/70 hover:text-white hover:bg-white/10">
                  Pricing
                </Button>
              </div>
            </div>
          </nav>

          {children}
        </div>
      </body>
    </html>
  )
} 
